### ISSUE TITLE
"Update available" is shown in the lower right, but the link responds returns a 404 error.

### ISSUE THREAD

**Issue by fractalbrain** [wildfoundry/dataplicity-porthole-releases-osx#2]
@barfle

"Update available" is shown in the lower right.  Link responds with a 404 error.  See: https://github.com/wildfoundry/dataplicity-porthole-releases-osx/releases/download/1.5/DataplicityPortholeSetup.pkg

**Comment by barfle** [comment]
Thanks for the report. A typo here 1.4 is in fact latest. We are patching this up now.

Best
Elliot

**Comment by barfle** [comment]
Fixed
