### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by ghost** [wildfoundry/dataplicity-porthole-releases-osx#6]
Hello,

I'm trying open it on my mac mojave version 10.14 (18A391)
![image](https://user-images.githubusercontent.com/8284586/48029664-9a9e0980-e103-11e8-949a-4a47dc7e0a1c.png)

Thanks!

**Comment by barfle** [comment]
Hi there,
Can you please send to support@dataplicity.com the contents of the report?  Unfortunately we can't tell much from the screenshot alone.
Best,
Elliot

**Comment by ghost** [comment]
Of course.
I sent it.

**Comment by barfle** [comment]
Bug report received.  Issue is confirmed.  I suspect this might be a new error - can you please try the previous version and see if that has the same issue for you?

Best,
Elliot.

**Comment by ghost** [comment]
I tried version 1.5 and it works.

**Comment by barfle** [comment]
We have released a new version today. Can you please check it also works? There are a few other bug fixes thrown in for good measure.

**Comment by ghost** [comment]
@barfle Thanks it works!

**Comment by barfle** [comment]
Awesome thanks for helping us out :)
