### ISSUE TITLE
auto updating to version 1.6

### ISSUE THREAD

**Issue by core-code** [wildfoundry/dataplicity-porthole-releases-osx#9]
there is no 1.6 entry in the feed here
https://rink.hockeyapp.net/api/2/apps/0d06fec05c134d28a736937f1f485272

**Comment by PawelErnestLuczak** [comment]
@core-code i am wondering why it is redirecting you to hockey.
1.6 was always here:
https://github.com/wildfoundry/dataplicity-porthole-releases-osx/tree/master/1.6

Could you describe what the app and browser do after you click update link inside the app? 
Your link contains kind of RSS feed.

**Comment by core-code** [comment]
closing invalid
